import os

# Make the preview directory
os.makedirs("preview", exist_ok=True)

# Generate a basic HTML file
html_content = '''
<!DOCTYPE html>
<html>
<head>
    <title>Preview Environment</title>
    <style>
        body { font-family: Arial, sans-serif; padding: 40px; }
        h1 { color: #2c3e50; }
        p { font-size: 18px; }
    </style>
</head>
<body>
    <h1>Hello from a GitHub PR Preview!</h1>
    <p>This static page was generated by a GitHub Actions workflow on a pull request.</p>
</body>
</html>
'''

# Write to preview/index.html
with open("preview/index.html", "w") as f:
    f.write(html_content)
